# Generated by Django 4.2.7 on 2025-11-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_course_instructor_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (4.3)'), ('A', 'A (4.0)'), ('A-', 'A- (3.7)'), ('B+', 'B+ (3.3)'), ('B', 'B (3.0)'), ('B-', 'B- (2.7)'), ('C+', 'C+ (2.3)'), ('C', 'C (2.0)'), ('C-', 'C- (1.7)'), ('D+', 'D+ (1.3)'), ('D', 'D (1.0)'), ('D-', 'D- (0.7)'), ('F', 'F (0.0)'), ('I', 'I (Incomplete)')], max_length=2, null=True),
        ),
    ]
