# Generated by Django 4.2.7 on 2025-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('student', 'Student Self-Registration'), ('admin', 'Admin Assignment')], default='student', max_length=20),
        ),
    ]
