# Generated by Django 4.2.7 on 2025-11-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (4.00)'), ('A', 'A (4.00)'), ('A-', 'A- (3.75)'), ('B+', 'B+ (3.50)'), ('B', 'B (3.00)'), ('B-', 'B- (2.75)'), ('C+', 'C+ (2.50)'), ('C', 'C (2.00)'), ('C-', 'C- (1.75)'), ('D', 'D (1.00)'), ('F', 'F (0.00)'), ('I', 'I (Incomplete)')], max_length=2, null=True),
        ),
    ]
